on:
  push:
    branches:
      - main

name: Package and deploy simple web app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    # deploy web app using publish profile credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: sunpipe
        package: devops
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_367d0031 }}